import {
	Activity,
	AlertCircle,
	AlertTriangle,
	ArrowRight,
	Bell,
	Bookmark,
	BookOpen,
	Braces,
	CaseSensitive,
	Check,
	CheckCheck,
	ChevronDown,
	ChevronRight,
	Circle,
	CircleCheck,
	CircleHelp,
	CircleSlash,
	CircleX,
	ClipboardList,
	CloudDownload,
	CloudUpload,
	Copy,
	CreditCard,
	ExternalLink,
	Eye,
	File,
	FileCode2,
	FileDiff,
	FilePlus2,
	Files,
	Folder,
	FolderOpen,
	FolderSymlink,
	FoldVertical,
	Funnel,
	GitBranch,
	Github,
	GitMerge,
	Globe,
	History,
	ImageUp,
	Info,
	KeyRound,
	Lightbulb,
	Link2,
	LoaderCircle,
	Lock,
	type LucideIcon,
	MessageSquareText,
	MessagesSquare,
	Pen,
	Pencil,
	Plus,
	RefreshCw,
	Regex,
	RotateCcw,
	Scale,
	ScanSearch,
	Search,
	Send,
	Server,
	Settings,
	SquareArrowOutUpRight,
	SquareMinus,
	SquareTerminal,
	Star,
	Terminal,
	Trash2,
	TriangleAlert,
	Undo2,
	UserCircle,
	WholeWord,
	X,
	Zap,
} from "lucide-react"

/** Curated aliases that keep legacy call sites on one coherent stroke system. */
export const LUCIDE_ICONS: Record<string, LucideIcon> = {
	Activity,
	add: Plus,
	AlertCircle,
	AlertCircleIcon: AlertCircle,
	AlertTriangle,
	ArrowRightIcon: ArrowRight,
	Bell,
	bell: Bell,
	BellIcon: Bell,
	Bookmark,
	BookmarkIcon: Bookmark,
	book: BookOpen,
	"case-sensitive": CaseSensitive,
	Check,
	check: Check,
	CheckIcon: Check,
	CheckCheck,
	CheckCheckIcon: CheckCheck,
	ChevronDown,
	"chevron-down": ChevronDown,
	ChevronDownIcon: ChevronDown,
	ChevronRight,
	"chevron-right": ChevronRight,
	ChevronRightIcon: ChevronRight,
	Circle,
	CircleIcon: Circle,
	CircleCheck,
	CircleCheckIcon: CircleCheck,
	CircleSlash,
	CircleSlashIcon: CircleSlash,
	CircleX,
	CircleXIcon: CircleX,
	close: X,
	"cloud-download": CloudDownload,
	"cloud-upload": CloudUpload,
	"comment-discussion": MessagesSquare,
	Copy,
	copy: Copy,
	CopyIcon: Copy,
	"credit-card": CreditCard,
	"debug-restart": RotateCcw,
	"diff-multiple": Files,
	"diff-single": FileDiff,
	discard: Undo2,
	edit: Pencil,
	error: CircleX,
	ExternalLink,
	Eye,
	EyeIcon: Eye,
	feedback: MessageSquareText,
	file: File,
	FileCode2,
	FileCode2Icon: FileCode2,
	FilePlus2,
	FilePlus2Icon: FilePlus2,
	files: Files,
	"file-symlink-directory": FolderSymlink,
	FoldVertical,
	FoldVerticalIcon: FoldVertical,
	folder: Folder,
	FolderOpen,
	"folder-opened": FolderOpen,
	Funnel,
	FunnelIcon: Funnel,
	GitBranch,
	GitMerge,
	github: Github,
	globe: Globe,
	History,
	HistoryIcon: History,
	ImageUp,
	ImageUpIcon: ImageUp,
	Info,
	info: Info,
	InfoIcon: Info,
	inspect: ScanSearch,
	key: KeyRound,
	law: Scale,
	Lightbulb,
	LightbulbIcon: Lightbulb,
	Link2,
	Link2Icon: Link2,
	loading: LoaderCircle,
	LoaderCircle,
	LoaderCircleIcon: LoaderCircle,
	lock: Lock,
	"new-file": FilePlus2,
	output: ClipboardList,
	Pen,
	PenIcon: Pen,
	Pencil,
	PencilIcon: Pencil,
	Plus,
	PlusIcon: Plus,
	pulse: Activity,
	question: CircleHelp,
	refresh: RefreshCw,
	regex: Regex,
	Search,
	search: Search,
	SearchIcon: Search,
	send: Send,
	server: Server,
	"settings-gear": Settings,
	SettingsIcon: Settings,
	SquareArrowOutUpRightIcon: SquareArrowOutUpRight,
	SquareMinus,
	SquareMinusIcon: SquareMinus,
	Star,
	"star-full": Star,
	StarIcon: Star,
	"symbol-event": Zap,
	"symbol-file": FileCode2,
	"symbol-method": Braces,
	Terminal,
	terminal: SquareTerminal,
	"terminal-bash": SquareTerminal,
	TerminalIcon: Terminal,
	Trash2,
	Trash2Icon: Trash2,
	TriangleAlert,
	TriangleAlertIcon: TriangleAlert,
	UserCircle,
	UserCircleIcon: UserCircle,
	warning: TriangleAlert,
	"whole-word": WholeWord,
	X,
	x: X,
	Zap,
	ZapIcon: Zap,
}
