name: Actionlint

on:
  pull_request:
    paths:
      - ".github/workflows/**"
      - ".github/actions/**"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/**"
      - ".github/actions/**"

permissions:
  contents: read

concurrency:
  group: actionlint-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download actionlint
        id: get_actionlint
        run: bash <(curl -fsSL https://raw.githubusercontent.com/rhysd/actionlint/v1.7.12/scripts/download-actionlint.bash) 1.7.12
        shell: bash
      - name: Run actionlint
        run: ${{ steps.get_actionlint.outputs.executable }} -color -config-file .github/actionlint.yaml -shellcheck=
        shell: bash
